AWSTemplateFormatVersion: '2010-09-09'
Resources:
  RequestQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      QueueName: RequestQueue

  RequestQueuePolicy:
    Type: 'AWS::SQS::QueuePolicy'
    Properties:
      Queues:
        - !Ref RequestQueue
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sqs:SendMessage
            Resource: !GetAtt RequestQueue.Arn

Outputs:
  RequestQueueUrl:
    Value: !Ref RequestQueue
    Export:
      Name: RequestQueueUrl
