AWSTemplateFormatVersion: '2010-09-09'
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: sample-aws-sqs-lambda-functions-template

Outputs:
  S3BucketNameCFn:
    Value: !Ref S3Bucket
    Export:
      Name: S3BucketNameCFn
